package opus

var CeltConstants = struct {
	Q15ONE                 int
	CELT_SIG_SCALE         float32
	SIG_SHIFT              int
	NORM_SCALING           int
	DB_SHIFT               int
	EPSILON                int
	VERY_SMALL             int
	VERY_LARGE16           int16
	Q15_ONE                int16
	COMBFILTER_MAXPERIOD   int
	COMBFILTER_MINPERIOD   int
	DECODE_BUFFER_SIZE     int
	BITALLOC_SIZE          int
	MAX_PERIOD             int
	TOTAL_MODES            int
	MAX_PSEUDO             int
	LOG_MAX_PSEUDO         int
	CELT_MAX_PULSES        int
	MAX_FINE_BITS          int
	FINE_OFFSET            int
	QTHETA_OFFSET          int
	QTHETA_OFFSET_TWOPHASE int
	PLC_PITCH_LAG_MAX      int
	PLC_PITCH_LAG_MIN      int
	LPC_ORDER              int
}{
	Q15ONE:                 32767,
	CELT_SIG_SCALE:         32768.0,
	SIG_SHIFT:              12,
	NORM_SCALING:           16384,
	DB_SHIFT:               10,
	EPSILON:                1,
	VERY_SMALL:             0,
	VERY_LARGE16:           32767,
	Q15_ONE:                32767,
	COMBFILTER_MAXPERIOD:   1024,
	COMBFILTER_MINPERIOD:   15,
	DECODE_BUFFER_SIZE:     2048,
	BITALLOC_SIZE:          11,
	MAX_PERIOD:             1024,
	TOTAL_MODES:            1,
	MAX_PSEUDO:             40,
	LOG_MAX_PSEUDO:         6,
	CELT_MAX_PULSES:        128,
	MAX_FINE_BITS:          8,
	FINE_OFFSET:            21,
	QTHETA_OFFSET:          4,
	QTHETA_OFFSET_TWOPHASE: 16,
	PLC_PITCH_LAG_MAX:      720,
	PLC_PITCH_LAG_MIN:      100,
	LPC_ORDER:              24,
}
