package opus

var TuningParameters = struct {
	BITRESERVOIR_DECAY_TIME_MS                int
	FIND_PITCH_WHITE_NOISE_FRACTION           float32
	FIND_PITCH_BANDWIDTH_EXPANSION            float32
	FIND_LPC_COND_FAC                         float32
	FIND_LTP_COND_FAC                         float32
	LTP_DAMPING                               float32
	LTP_SMOOTHING                             float32
	MU_LTP_QUANT_NB                           float32
	MU_LTP_QUANT_MB                           float32
	MU_LTP_QUANT_WB                           float32
	MAX_SUM_LOG_GAIN_DB                       float32
	VARIABLE_HP_SMTH_COEF1                    float32
	VARIABLE_HP_SMTH_COEF2                    float32
	VARIABLE_HP_MAX_DELTA_FREQ                float32
	VARIABLE_HP_MIN_CUTOFF_HZ                 int
	VARIABLE_HP_MAX_CUTOFF_HZ                 int
	SPEECH_ACTIVITY_DTX_THRES                 float32
	LBRR_SPEECH_ACTIVITY_THRES                float32
	BG_SNR_DECR_dB                            float32
	HARM_SNR_INCR_dB                          float32
	SPARSE_SNR_INCR_dB                        float32
	SPARSENESS_THRESHOLD_QNT_OFFSET           float32
	WARPING_MULTIPLIER                        float32
	SHAPE_WHITE_NOISE_FRACTION                float32
	BANDWIDTH_EXPANSION                       float32
	LOW_RATE_BANDWIDTH_EXPANSION_DELTA        float32
	LOW_RATE_HARMONIC_BOOST                   float32
	LOW_INPUT_QUALITY_HARMONIC_BOOST          float32
	HARMONIC_SHAPING                          float32
	HIGH_RATE_OR_LOW_QUALITY_HARMONIC_SHAPING float32
	HP_NOISE_COEF                             float32
	HARM_HP_NOISE_COEF                        float32
	INPUT_TILT                                float32
	HIGH_RATE_INPUT_TILT                      float32
	LOW_FREQ_SHAPING                          float32
	LOW_QUALITY_LOW_FREQ_SHAPING_DECR         float32
	SUBFR_SMTH_COEF                           float32
	LAMBDA_OFFSET                             float32
	LAMBDA_SPEECH_ACT                         float32
	LAMBDA_DELAYED_DECISIONS                  float32
	LAMBDA_INPUT_QUALITY                      float32
	LAMBDA_CODING_QUALITY                     float32
	LAMBDA_QUANT_OFFSET                       float32
	REDUCE_BITRATE_10_MS_BPS                  int
	MAX_BANDWIDTH_SWITCH_DELAY_MS             int
}{
	BITRESERVOIR_DECAY_TIME_MS:                500,
	FIND_PITCH_WHITE_NOISE_FRACTION:           1e-3,
	FIND_PITCH_BANDWIDTH_EXPANSION:            0.99,
	FIND_LPC_COND_FAC:                         1e-5,
	FIND_LTP_COND_FAC:                         1e-5,
	LTP_DAMPING:                               0.05,
	LTP_SMOOTHING:                             0.1,
	MU_LTP_QUANT_NB:                           0.03,
	MU_LTP_QUANT_MB:                           0.025,
	MU_LTP_QUANT_WB:                           0.02,
	MAX_SUM_LOG_GAIN_DB:                       250.0,
	VARIABLE_HP_SMTH_COEF1:                    0.1,
	VARIABLE_HP_SMTH_COEF2:                    0.015,
	VARIABLE_HP_MAX_DELTA_FREQ:                0.4,
	VARIABLE_HP_MIN_CUTOFF_HZ:                 60,
	VARIABLE_HP_MAX_CUTOFF_HZ:                 100,
	SPEECH_ACTIVITY_DTX_THRES:                 0.05,
	LBRR_SPEECH_ACTIVITY_THRES:                0.3,
	BG_SNR_DECR_dB:                            2.0,
	HARM_SNR_INCR_dB:                          2.0,
	SPARSE_SNR_INCR_dB:                        2.0,
	SPARSENESS_THRESHOLD_QNT_OFFSET:           0.75,
	WARPING_MULTIPLIER:                        0.015,
	SHAPE_WHITE_NOISE_FRACTION:                5e-5,
	BANDWIDTH_EXPANSION:                       0.95,
	LOW_RATE_BANDWIDTH_EXPANSION_DELTA:        0.01,
	LOW_RATE_HARMONIC_BOOST:                   0.1,
	LOW_INPUT_QUALITY_HARMONIC_BOOST:          0.1,
	HARMONIC_SHAPING:                          0.3,
	HIGH_RATE_OR_LOW_QUALITY_HARMONIC_SHAPING: 0.2,
	HP_NOISE_COEF:                             0.25,
	HARM_HP_NOISE_COEF:                        0.35,
	INPUT_TILT:                                0.05,
	HIGH_RATE_INPUT_TILT:                      0.1,
	LOW_FREQ_SHAPING:                          4.0,
	LOW_QUALITY_LOW_FREQ_SHAPING_DECR:         0.5,
	SUBFR_SMTH_COEF:                           0.4,
	LAMBDA_OFFSET:                             1.2,
	LAMBDA_SPEECH_ACT:                         -0.2,
	LAMBDA_DELAYED_DECISIONS:                  -0.05,
	LAMBDA_INPUT_QUALITY:                      -0.1,
	LAMBDA_CODING_QUALITY:                     -0.2,
	LAMBDA_QUANT_OFFSET:                       0.8,
	REDUCE_BITRATE_10_MS_BPS:                  2200,
	MAX_BANDWIDTH_SWITCH_DELAY_MS:             5000,
}
